### ISSUE TITLE
Compatibility Julia0.4; test/runtests.jl fails

### ISSUE THREAD

**Issue by AlainLich** [JuliaPackaging/MetadataTools.jl#3]
Hi,

I am  trying to use MetadataTools under Julia 0.4. 
1. found an issue with Tuple syntax, corrected it, see git diff below
2. now getting the following error running `runtests.jl`: (please note that I have Gadfly installed, so the issue is not related to the choice of test example in insn `sg = get_pkg_dep_graph(pkgs["Gadfly"], g)`)

```
Julia4 runtests.jl 
WARNING: deprecated syntax "{}" at /home/alain/.julia/v0.4/MetadataTools/src/MetadataTools.jl:248.
Use "[]" instead.
Warning: could not import Base.put into Requests
WARNING: This version of the GnuTLS library (3.2.11) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.
ERROR: LoadError: BoundsError: attempt to access 628-element Array{Int64,1}:
 0
 0
 ....
 0
  at index [0]
 in traverse_graph at /home/alain/.julia/v0.4/Graphs/src/breadth_first_visit.jl:55
 in get_pkg_dep_graph at /home/alain/.julia/v0.4/MetadataTools/src/MetadataTools.jl:341
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
while loading /home/alain/src/Julia/MetadataTools.jl/test/runtests.jl, in expression starting on line 6
```

Please advise.

---

Git diff for correcting _Tuple_ syntax issue:
```--- a/src/MetadataTools.jl
+++ b/src/MetadataTools.jl
@@ -8,6 +8,7 @@
 module MetadataTools

 import Requests, JSON, Graphs
+using Compat

 export get_pkg, get_all_pkg, get_upper_limit, get_pkg_info
 export get_pkgs_dep_graph, get_pkg_dep_graph
@@ -62,7 +63,7 @@ immutable PkgInfo
     homepage::String
     stars::Int
     watchers::Int
-    contributors::Vector{(Int,Contributor)}  # (commit_count,Contrib.)
-    contributors::Vector{@compat Tuple{Int,Contributor}}  # (commit_count,Contrib.)
  end
  ###### 
  
  @@ -341,4 +342,4 @@ function get_pkg_dep_graph(pkg::PkgMeta, dep_graph::PkgGraph)
   return v.sub_graph
  end

-end  # module
\ No newline at end of file
+end  # module

```
```

**Comment by IainNZ** [comment]
Hi @AlainLich, I've unfortunately let entropy get the best of this package. I've fixed most of these things locally, just haven't pushed them up and tagged them. Since I know someone is interested, I'll try to get to that sooner than I had planned!
I think there is something that has changed with how Graphs worked - I've switched to LightGraphs, which I find easier to reason about.

**Comment by AlainLich** [comment]
Hi,
just traced the issue to an error in Graphs.jl, and issued a PR https://github.com/JuliaLang/Graphs.jl/pull/182 to correct it. Now MetadataTools passes its `test/runtest.jl` .
